name: Deploy Rails App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH Agent
        run: |
          echo "🚀 Setting up SSH agent"
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Run Deployment Script
        run: |
          echo "🚀 Running deployment script"
          chmod +x /home/staging/deploy.sh
          /home/staging/deploy.sh
          echo "🚀 Deployment complete!"
