name: Deploy Rails App

on:
  push:
    branches:
      - main  # Deploy when the main branch is updated

jobs:
  deploy:
    runs-on: self-hosted  # Use the self-hosted runner instead of GitHub-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Deployment Script
        run: |
          echo "🚀 Running deployment script from /home/staging/"
          sudo chmod +x /home/staging/deploy.sh
          sudo /home/staging/deploy.sh
          echo "🚀 Deployment complete!"
