name: Deploy Rails App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Deployment Script
        run: |
          echo "🚀 Running deployment script"
          echo ${{ secrets.SUDO_PASSWORD }} | sudo -S chmod +x /home/staging/deploy.sh
          echo ${{ secrets.SUDO_PASSWORD }} | sudo -S /home/staging/deploy.sh
          echo "🚀 Deployment complete!"
